name: Check New Pull Request

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ '**' ]

jobs:
  build:
    name: Check if passes all requirements
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        poetry-version: [ 1.5.0 ]
        os: [ ubuntu-latest ]

    steps:
      - uses: actions/checkout@v3
      - name: Set up Python 3.10
        uses: actions/setup-python@v3
        with:
          python-version: "3.10"

      - name: Run image
        uses: abatilo/actions-poetry@v2
        with:
          poetry-version: ${{ matrix.poetry-version }}

      - name: build esmf-aspect
        run: |
          cd core/esmf-aspect-meta-model-python
          poetry install
          poetry run download-samm-release
          poetry build

      - name: run tests
        run: |
          cd core/esmf-aspect-meta-model-python
          poetry run pytest

      - name: run MyPy
        run: |
          cd core/esmf-aspect-meta-model-python
          poetry run mypy .

      - name: run black
        uses: psf/black@stable
        with:
          options: "--check --line-length=160"
